### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by zachlatta** [hackedu/pm#14]
#### Sprint Goals
1. Create website sitemap & rough styleguide
2. Complete individual business cards
3. Finish first draft of our trademark application
4. Create timeline from now until August for our club in a box
5. zachlatta/fundraising#7
#### Sprint Participants

@benzweig @gemmabusoni @MaxWofford @jonleung @zachlatta
#### Sprint Deliverables
- [ ] Website
  - [x] Sitemap hackedu/hackedu#79 (@benzweig, @MaxWofford)
  - [ ] Rough style guide for website hackedu/hackedu#80 (@benzweig, @MaxWofford)
- [ ] Design
  - [ ] Business cards designed & completed hackedu/docs#30 (@benzweig)
    - [ ] Email business card printers for in-kind donations zachlatta/fundraising#3 (@zachlatta)
  - [x] hackEDU logo redesign hackedu/docs#31 (@benzweig)
    - [ ] send to @gemmabusoni
- [x] Club in a box
  - [x] Plan Lincoln club meeting hackedu/club-in-a-box#7 (@jonleung, @MaxWofford)
  - [x] Create timeline hackedu/club-in-a-box#5 (@jonleung)
  - [x] Plan Lowell club meeting hackedu/club-in-a-box#6 (@jonleung, @MaxWofford)
- [ ] Other
  - [ ] Design and deliver git workflow meeting for hackEDU's processes on GitHub hackedu/docs#32 (@zachlatta, @jonleung)
  - [ ] First draft of trademark application hackedu/docs#33 (@gemmabusoni)
  - [x] zachlatta/fundraising#7 (@zachlatta)

---
##### EDIT Wed April 15th - @jonleung
- [x] Plan time for next sprint discuss
  - [x] hackedu/pm#13 (@jonleung)

**Comment by maxwofford** [comment]
@zachlatta the first "Plan Lowell club meeting" should be for "Lincoln club meeting"

**Comment by zachlatta** [comment]
@MaxWofford updated!

**Comment by jonleung** [comment]
Added https://github.com/hackedu/pm/issues/13 and assigned @jonleung to it

**Comment by jonleung** [comment]
Finished my sprint tasks for the week! Wohoo!

**Comment by zachlatta** [comment]
Closing for now.
