### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by jonleung** [hackedu/pm#16]
![image](http://i.imgur.com/WrhtkU0.jpg)

[Raw notes from the call](notes/sprint_002_04_27_15_notes.txt)
## Sprint Participants

@amandadoan @amysorto @bogidon @cydrobolt @jonleung @xeonjake 
#### Amanda

Learn about Github
- [x] Finish at least 1 Github tutorial hackedu/hackedu#16
#### Amy

Elizabeth High School Club
- [ ] Come up with 3 projects that her club can work on and will write up a 3 sentence description hackedu/hackedu#17
- [ ] Figure out how to use cloud9 by sending a text message with Twilio through it. hackedu/hackedu#18
- [ ] Will review @xeonjake's budget by May 1st after he sends it to her by April 29th
#### Bogdan
- [ ] [Will ship a medium blogpost on how he got an internship offer hackedu/hackedu#19
#### Jiahow
- [ ] Finish a draft of the club budget by April 30th hackedu/hackedu#20
  - [ ] Send @amysorto the Club Budget by the 29th
- _Not a commitment: NFC Project Attendance Project_
#### Jonathan (will need to reduce list)

Personal
- [ ] **Ship a first packged version of Club in a Box**
  - [ ] **Spreading Knowledge of hackEDU Processes**
    - [x] **Misc**
      - [x] Send out survey for this sprint meeting to everyone who is a part of the sprint
    - [x] **Update Communications Channels**:
      - [ ] Github
        - [ ] Create a file in the [hackEDU repo](http://github.com/hackedu/hackedu) where club leaders can add their info to a row in the CSV file with First, Last, Github, Website, Facebook [similar to this one](https://github.com/hshackers/docs/blob/master/members.csv).
      - [ ] IRC
      - [ ] Facebook Group
      - [ ] Internal Sprints
      - [ ] Club Leader Sprints
    - [ ] **Create Onboarding Process Checklist**
    - [ ] **Sprints**
      - [ ] Create Sprint Checklist
      - [ ] Update pm/README.md for club leader readibility
      - [ ] Create club leader sprints
        - [ ] Create a weekly issue
        - [ ] Create a proper Google Hangout time 5:30pm - 6:30pm is hackEDU leaders time
      - [ ] Schedule next sprint discuss
        - [ ] 7:00pm - 8:00pm is Sprint Discussion
    - [ ] **Articulate the most important issues in order**         - [ ] What do you actually do in a club?
      - [x] Retention
      - [ ] Getting New Users
  - [ ] **Spreading Knwoledge of where we are at**
    - [ ] We currently need your help to build hackEDU
    - [ ] We are going to focus on doing these things, please make a pull request
  - [ ] **Spreading Knowledge of Curriculum**
    - [ ] Cloud 9
    - [ ] Blogpost talking about Google based development
    - [ ] Challenges I-III
  - [ ] **Spreading Club Administration Help**
    - [x] Attendance
    - [ ] Club Constitutions
    - [ ] Club
    - [ ] Things that are useful from the proposal for Richard
- [ ] **Internships**
  - [ ] Organize Internships Workshop
  - [ ] Just initially by posting [obsessed.jonl.org](http://obsessed.jonl.org)
  - [ ] Gather Resumes
  - [ ] Respond to this [FB post](https://www.facebook.com/groups/1501083703514499/permalink/1577049445917924/)
- [ ] **Gather Base Metrics Of Existing Clubs**

**Re-engage Club Leaders**
- [ ] Re-engage club leaders with current efforts On The Above

**Partnerships**
- [ ] Submit Github Partnership 

**Personal**
- [ ] Inbox 0
  - [ ] Email
  - [ ] Facebook Messenger
  - [ ] Asana

**Notes**
- [ ] Review All Notes

**Things To Ask For Help On**
- [ ] Why you should encourage your son or daughter to go to a hackathon
- [ ] Gather Club Constitution / Values
- [ ] Other Things
## Backlog
- [ ] Free GitHub repos zachlatta/fundraising#6

---

EDIT (04.30.15) @zachlatta: Create backlog and add zachlatta/fundraising#6 to it

**Comment by zachlatta** [comment]
Closing for now.
