### ISSUE TITLE
Sprint 4

### ISSUE THREAD

**Issue by zachlatta** [hackedu/pm#18]
#### Sprint Goals
1. Reconnect with club leaders and ensure proper succession
2. Build MVP of club in a box for introductory materials
3. Make progress with fundraising, identify foundations and individuals and
   get connected with them.
4. Onboard @wilsonhsieh
#### Sprint Participants

@xeonjake @Cydrobolt @wilsonhsieh @jonleung @zachlatta
#### Sprint Deliverables
- [ ] Club in a box
  - [ ] Collect data from club leaders and make sure everyone, if needed, has
    a successor hackedu/hackedu#21 (@jonleung)
  - [ ] Make Twilio workshops accessible hackedu/hackedu#22 (@jonleung)
  - [ ] Write blog post on the "Google philosophy" (@jonleung)
  - [ ] Finish the _Joining Community_ slides (@jonleung)
  - [ ] Basic stuff for starting clubs
    - [ ] Club constitution hackedu/hackedu#15 (@jonleung)
    - [ ] Club budget hackedu/hackedu#20 (@jonleung)
    - [ ] Attendance sheet hackedu/hackedu#23 (@jonleung)
  - [ ] Lesson structure document hackedu/hackedu#24 (@jonleung)
- [ ] Fundraising
  - [ ] Lunch with Google zachlatta/fundraising#18 (@zachlatta)
  - [ ] Identify and find contacts at potential education foundations
    zachlatta/fundraising#19 (@zachlatta)
  - [ ] Identify potential donors that Richard has connections with
    zachlatta/fundraising#20 (@zachlatta)
  - [x] Get intros from Quinn to potential donors (@zachlatta)
  - [x] Get intros from Ryan to potential donors (@zachlatta)
  - [ ] Audible free accounts zachlatta/fundraising#21 (@zachlatta)
  - [x] Create list of potential donors from your network
    zachlatta/fundraising#22 (@jonleung)
    - [ ] Write and send emails to reach out to @jonleung's potential donors
      (@zachlatta)
  - [ ] Get introduction to Microsoft (@zachlatta)
  - [ ] Get introduction to the Intel Education Foundation from Austin Carvey
- [ ] Other
  - [x] Read through documentation on GitHub & talk to @zachlatta/@jonleung to
    understand where we're at (@wilsonhsieh)
  - [ ] Identify the biggest needs in the organization (@wilsonhsieh)
  - [ ] Put together markdown lesson plan for FizzBuzz workshop
    hackedu/hackedu#25 (@Cydrobolt)
  - [ ] Convert club documents to GitHub markdown (@xeonjake)
    - [ ] Club constitution
    - [ ] Club budgets (may be related to hackedu/hackedu#20)
  - [x] Create IRCCloud accounts for @amysorto, @xeonjake, and @wilsonhsieh
    (@zachlatta)
  - [x] Add @wilsonhsieh to GitHub team (@zachlatta)
  - [ ] Send things to @xeonjake and @Cydrobolt (@jonleung)
  - [ ] Send out sprint discussion survey to @xeonjake, @Cydrobolt,
    @wilsonhsieh, @amysorto, @jonleung, and @zachlatta (@jonleung)

---
- [ ] Backlog
  - [ ] Google Adwords zachlatta/fundraising#23 (@zachlatta)
  - [ ] Newsletter hackedu/meta#40 (@zachlatta)
  - [ ] Clean up migrated materials hackedu/hackedu#14 (@jonleung)
  - [ ] Create separate Google Hangouts URLs for more partytimes hackedu/meta#39 (@zachlatta)
  - [x] Respond to HP zachlatta/fundraising#14 (@zachlatta)
  - [ ] Apply to the Open Society Youth Fellowship zachlatta/fundraising#24 (@zachlatta)
