### ISSUE TITLE
Sprint 5

### ISSUE THREAD

**Issue by zachlatta** [hackedu/pm#19]
#### Sprint Goals
1. Begin process of finding a venue and acquiring students for summer program
2. Explicitly define the target outcome of clubs and figure out how to emulate
   that with summer program
3. Continue fundraising/start getting more money in the bank
#### Sprint Participants

@wilsonhsieh @jonleung @MaxWofford @zachlatta @xeonjake
#### Sprint Deliverables
- [ ] Club in a box
  - [ ] Collect data from club leaders and make sure everyone, if needed, has a successor hackedu/hackedu#21 (@MaxWofford)
  - [ ] Explicitly define the target outcome of a club (@jonleung)
  - [ ] Summer program
    - [x] Create budget (@MaxWofford)
    - [ ] Start finding a venue (@MaxWofford)
    - [x] Put together website content (@MaxWofford)
    - [ ] Figure out how to leverage summer camp to figure out what to put in the club in a box
- [ ] Fundraising
  - [ ] Get introduction to Microsoft (@zachlatta)
  - [ ] Get introduction the Intel Foundation from Austin Carvey (@zachlatta)
  - [ ] Meet with and find connections with Alana (@zachlatta)
  - [ ] Identify connections through Lonsdale (@zachlatta)
  - [ ] In-kind donations
    - [ ] Audible zachlatta/fundraising#21 (@zachlatta)
    - [ ] Google Adwords zachlatta/fundraising#23 (@zachlatta)
- [ ] Other
  - [ ] Get back to people about internships, talk to @zachlatta first (@jonleung)
  - [x] Have coffee with the team (@wilsonhsieh)
    - [x] Find a time that works for everyone on the team (@zachlatta)
  - [ ] Write email with @zachlatta to send out for sponsorship (@xeonjake)
    - [ ] Figure out what things are needed from sponsors (domains, etc) (@xeonjake)
  - [ ] Begin work on club website (@xeonjake)
  - [ ] Modify readme of `pm` repo to say that the sprint discuss link will also be posted on FB (@zachlatta)
  - [ ] Newsletter hackedu/meta#40 (@zachlatta)
  - [ ] Create separate Google Hangouts URLs for more partytimes hackedu/meta#39 (@zachlatta)
  - [ ] Make persistent URL for the sprint discuss (@zachlatta)
  - [ ] Debug Floobits and make sure editing works from the web interface (@zachlatta)

---
- [ ] Backlog
  - [ ] Clean up migrated materials hackedu/hackedu#14 (@jonleung)
  - [ ] Apply to the Open Society Youth Fellowship zachlatta/fundraising#24 (@zachlatta)
  - [x] Set up spreadsheet for tracking venues hackedu/hackedu#26 (@maxwofford)
  - [ ] Update club contact info in AirTable (@maxwofford)

**Comment by zachlatta** [comment]
Closing for now.
